import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  appHeaderMarkup,
  bottomNavigationMarkup,
  companyLogoMarkup
} from "../src/ui/foundation.js";
import { mixedDirectionMarkup } from "../src/ui/components.js";

const rootCss = read("../styles.css");
const mobileCss = read("../styles-mobile2.css");
const index = read("../index.html");
const serviceWorker = read("../service-worker.js");
const syncScript = read("../scripts/sync-deploy.mjs");
const foundationSource = read("../src/ui/foundation.js");
const mainSource = read("../src/main.js");
const componentSource = read("../src/ui/components.js");
const clipboardSource = read("../src/ui/clipboard.js");
const enhancerSource = read("../src/ui/mobile2Enhancer.js");
const premiumCss = read("../styles-premium.css");

for (const token of [
  "--bg:",
  "--surface:",
  "--line:",
  "--ink:",
  "--teal:",
  "--green:",
  "--amber:",
  "--red:",
  "--radius:",
  "--space-4:",
  "--tap:",
  "--app-max-width: 430px"
]) {
  assert.ok(rootCss.includes(token), `Foundation token missing: ${token}`);
}

assert.ok(rootCss.includes("env(safe-area-inset-top)"));
assert.ok(rootCss.includes("env(safe-area-inset-bottom)"));
assert.ok(rootCss.includes("overflow-x: hidden"));
assert.ok(rootCss.includes("unicode-bidi: isolate"));
assert.ok(rootCss.includes("min-height: var(--tap)"));
assert.ok(mobileCss.includes("--franklin-screen: 430px"));
assert.ok(mobileCss.includes("width: min(100%, var(--franklin-screen))"));
for (const color of ["#07080d", "#0b0d16", "#111422", "#1f253b", "#2dd4bf", "#fbbf24", "#f43f5e"]) {
  assert.ok(`${rootCss}\n${mobileCss}`.includes(color), `Figma color token missing: ${color}`);
}

const logo = companyLogoMarkup({ ticker: "MSFT", name: "Microsoft", logoUrl: "bad.png" });
assert.ok(logo.includes("data-company-logo"));
assert.ok(logo.includes("MSF"));
assert.ok(logo.includes("bad.png"));

const header = appHeaderMarkup({ title: "مكتبتي", isHome: true, language: "ar", label: (value) => value });
assert.ok(header.includes("mobile-app-header"));
assert.ok(header.includes("global-app-header"));
assert.ok(header.includes("إضافة سهم"));
assert.ok(header.includes("company-logo"));
assert.equal(header.includes("FRANKLIN RESEARCH"), false, "The global header must not render the legacy wordmark.");
assert.equal(header.includes("<strong>فرانكلين</strong>"), false, "The global header must remain logo-only.");
assert.ok(header.includes('role="img"'), "The logo-only brand must keep an accessible name.");

const nav = bottomNavigationMarkup({
  panels: [["home", "المكتبة"], ["history", "السجل"]],
  activePanel: "history",
  label: (value) => value
});
assert.ok(nav.includes('data-panel="history"'));
assert.ok(nav.includes('aria-current="page"'));

for (const generatedFile of ["styles-premium.css", "styles-v11-mobile-cleanup.css"]) {
  assert.ok(index.includes(generatedFile), `${generatedFile} must remain linked.`);
  assert.ok(syncScript.includes(`"${generatedFile}"`), `${generatedFile} must be generated by the deployment sync.`);
  assert.ok(serviceWorker.includes(`"./${generatedFile}"`), `${generatedFile} must be included in the frontend cache.`);
}

assert.ok(serviceWorker.includes('"./src/ui/foundation.js"'));
assert.ok(mainSource.includes('loadOptional("./ui/mobile2Enhancer.js"'));
assert.ok(mainSource.includes('loadOptional("./ui/quarterlyResultsEnhancer.js"'));
assert.equal(/localStorage|indexedDB|removeItem|\.clear\s*\(/.test(foundationSource), false, "Presentation primitives must not touch persisted data.");

assert.ok(componentSource.includes('class="library-hero"'), "Investment Library identity must remain visible on Home.");
assert.ok(componentSource.includes('class="investment-library-summary"'), "Home must retain its compact portfolio indicators.");
assert.ok(componentSource.includes("companyLogoMarkup({"), "Library and report identity must use the shared logo primitive.");
assert.ok(componentSource.includes('class="qgr-score-visual"'), "Report score rows must retain their compact numeric scores.");
assert.equal(componentSource.includes('style="width:${scoreMeterWidth(row.value)}%"'), false, "The obsolete colored score meter must not render in the report.");
assert.ok(componentSource.includes("export function mixedDirectionMarkup"), "Mixed Arabic/English prose must use the shared bidi formatter.");
assert.ok(componentSource.includes('<bdi dir="ltr">'), "English and financial fragments must be isolated inside Arabic prose.");
const mixedProse = mixedDirectionMarkup("تستفيد الشركة من Futu Holdings مع Base Case بقيمة $150.");
assert.ok(mixedProse.includes('<bdi dir="ltr">Futu Holdings</bdi>'));
assert.ok(mixedProse.includes('<bdi dir="ltr">Base Case</bdi>'));
assert.ok(mixedProse.includes('<bdi dir="ltr">$150</bdi>'));
const previewStart = componentSource.indexOf("function externalPreviewPanel");
const previewEnd = componentSource.indexOf("function externalInput", previewStart);
const previewSource = componentSource.slice(previewStart, previewEnd);
assert.equal(previewSource.includes('externalInput("scores.'), false, "ChatGPT-supplied score controls must not appear in the import preview.");
assert.equal(previewSource.includes('externalInput("decision.investmentScore"'), false, "The overall score control must not appear in the import preview.");
assert.ok(componentSource.includes('import { copyTextForMobile } from "./clipboard.js"'), "Prompt copying must use the tested clipboard adapter.");
assert.ok(clipboardSource.indexOf("clipboard?.writeText") < clipboardSource.indexOf('execCommand?.("copy")'), "Prompt copying must try the non-blocking Clipboard API before the legacy Safari fallback.");
assert.ok(componentSource.includes("installPromptCopyDelegation(root, store)"), "Prompt copying must use stable root delegation across owner-input rerenders.");
assert.ok(componentSource.includes("store.state.externalReportSelection?.ticker"), "Prompt copying must recover the selected report ticker outside the import form.");
assert.ok(componentSource.includes('root.querySelector("[data-external-ticker-hint]")?.addEventListener("input"'), "Ticker input must persist before owner price fields trigger a rerender.");
assert.ok(enhancerSource.includes('scenarioCell("Bear"') && enhancerSource.includes('scenarioCell("Base"') && enhancerSource.includes('scenarioCell("Bull"'));
assert.ok(premiumCss.includes(".stock-summary-metric.bear strong { color: var(--fr-red); }"));
assert.ok(premiumCss.includes(".stock-summary-metric.base strong { color: var(--fr-amber); }"));
assert.ok(premiumCss.includes(".stock-summary-metric.bull strong { color: var(--fr-green); }"));

console.log("Frontend foundation tests passed.");

function read(path) {
  return readFileSync(new URL(path, import.meta.url), "utf8");
}
