import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  appHeaderMarkup,
  bottomNavigationMarkup,
  companyLogoMarkup
} from "../src/ui/foundation.js";

const rootCss = read("../styles.css");
const mobileCss = read("../styles-mobile2.css");
const index = read("../index.html");
const serviceWorker = read("../service-worker.js");
const syncScript = read("../scripts/sync-deploy.mjs");
const foundationSource = read("../src/ui/foundation.js");
const mainSource = read("../src/main.js");
const componentSource = read("../src/ui/components.js");
const enhancerSource = read("../src/ui/mobile2Enhancer.js");
const premiumCss = read("../styles-premium.css");

for (const token of [
  "--bg:",
  "--surface:",
  "--line:",
  "--ink:",
  "--teal:",
  "--green:",
  "--amber:",
  "--red:",
  "--radius:",
  "--space-4:",
  "--tap:",
  "--app-max-width: 440px"
]) {
  assert.ok(rootCss.includes(token), `Foundation token missing: ${token}`);
}

assert.ok(rootCss.includes("env(safe-area-inset-top)"));
assert.ok(rootCss.includes("env(safe-area-inset-bottom)"));
assert.ok(rootCss.includes("overflow-x: hidden"));
assert.ok(rootCss.includes("unicode-bidi: isolate"));
assert.ok(rootCss.includes("min-height: var(--tap)"));
assert.ok(mobileCss.includes("max-width:var(--app-max-width)"));

const logo = companyLogoMarkup({ ticker: "MSFT", name: "Microsoft", logoUrl: "bad.png" });
assert.ok(logo.includes("data-company-logo"));
assert.ok(logo.includes("MSF"));
assert.ok(logo.includes("bad.png"));

const header = appHeaderMarkup({ title: "مكتبتي", isHome: true, language: "ar", label: (value) => value });
assert.ok(header.includes("mobile-app-header"));
assert.ok(header.includes("إضافة سهم"));
assert.ok(header.includes("company-logo"));

const nav = bottomNavigationMarkup({
  panels: [["home", "المكتبة"], ["history", "السجل"]],
  activePanel: "history",
  label: (value) => value
});
assert.ok(nav.includes('data-panel="history"'));
assert.ok(nav.includes('aria-current="page"'));

for (const generatedFile of ["styles-premium.css", "styles-v11-mobile-cleanup.css"]) {
  assert.ok(index.includes(generatedFile), `${generatedFile} must remain linked.`);
  assert.ok(syncScript.includes(`"${generatedFile}"`), `${generatedFile} must be generated by the deployment sync.`);
  assert.ok(serviceWorker.includes(`"./${generatedFile}"`), `${generatedFile} must be included in the frontend cache.`);
}

assert.ok(serviceWorker.includes('"./src/ui/foundation.js"'));
assert.ok(mainSource.includes('import "./ui/mobile2Enhancer.js"'));
assert.ok(mainSource.includes('import "./ui/quarterlyResultsEnhancer.js"'));
assert.equal(/localStorage|indexedDB|removeItem|\.clear\s*\(/.test(foundationSource), false, "Presentation primitives must not touch persisted data.");

assert.ok(componentSource.includes('class="library-hero"'), "Investment Library identity must remain visible on Home.");
assert.ok(componentSource.includes('class="investment-library-summary"'), "Home must retain its compact portfolio indicators.");
assert.ok(componentSource.includes("companyLogoMarkup({"), "Library and report identity must use the shared logo primitive.");
assert.ok(componentSource.includes('class="qgr-score-visual"'), "Report score rows must retain their visual indicators.");
assert.ok(enhancerSource.includes('scenarioCell("Bear"') && enhancerSource.includes('scenarioCell("Base"') && enhancerSource.includes('scenarioCell("Bull"'));
assert.ok(premiumCss.includes(".stock-summary-metric.bear strong { color: var(--fr-red); }"));
assert.ok(premiumCss.includes(".stock-summary-metric.base strong { color: var(--fr-amber); }"));
assert.ok(premiumCss.includes(".stock-summary-metric.bull strong { color: var(--fr-green); }"));

console.log("Frontend foundation tests passed.");

function read(path) {
  return readFileSync(new URL(path, import.meta.url), "utf8");
}
