import assert from "node:assert/strict";
import { buildFullAnalysisPrompt, FRANKLIN_INITIAL_PROMPT_VERSION } from "../src/externalAnalysis/chatgptContract.js";

const prompt = buildFullAnalysisPrompt({ tickerHint: "NVDA" });

assert.equal(FRANKLIN_INITIAL_PROMPT_VERSION, "franklin-initial-analysis-prompt/v3");
assert.ok(prompt.includes("FRANKLIN_INITIAL_ANALYSIS"));
assert.ok(prompt.includes("franklin-fair-value/v3"));
assert.ok(prompt.includes("fair-value-methodology/v2"));
assert.ok(prompt.includes("analysisType يجب أن يكون INITIAL"));
assert.ok(prompt.includes("nextRequirements.currentJustifiedValue"));
assert.ok(prompt.includes("QUARTER FORMAT GATE"));
assert.ok(prompt.includes('"FY2026 Q3"'));
assert.ok(prompt.includes('"Q3 FY2026"'));
assert.ok(prompt.includes("marketPrice.currency وvaluation.current.currency"));
assert.ok(prompt.includes("CANONICAL ENUM VALUES — MANDATORY"));
assert.ok(prompt.includes("strengths[].importance"));
assert.ok(prompt.includes("critical أو high أو medium أو low أو null"));
assert.ok(prompt.includes("latestQuarter.forwardOutlook.growthOutlook"));
assert.ok(prompt.includes("latestQuarter.forwardOutlook.managementTone"));
assert.ok(prompt.includes("forecast.materiality"));
assert.ok(prompt.includes("forecast.yearlyForecast.*.basis"));
assert.ok(prompt.includes("analyst_assumption"));
assert.ok(prompt.includes("company.securityUnit"));
assert.ok(prompt.includes("share أو ADS أو ADR أو unit"));
assert.ok(prompt.includes("GAAP عن non-GAAP"));
assert.ok(prompt.includes("Enterprise Value إلى Equity Value"));
assert.ok(prompt.includes("عدد الأسهم المخفف"));
assert.ok(prompt.includes("financialNormalization"));
assert.ok(prompt.includes("computedFairValue"));
assert.ok(prompt.includes("weightedMethodFairValue"));
assert.ok(prompt.includes("analystOverlayPct"));
assert.ok(prompt.includes("لا تصدر القرار من نسبة upside وحدها"));
assert.ok(prompt.includes("FILE DELIVERY — MANDATORY PRIMARY MODE"));
assert.ok(prompt.includes("downloadable UTF-8 JSON file"));
assert.ok(prompt.includes("franklin-NVDA-initial-analysis.json"));
assert.ok(prompt.includes("Do not print the completed JSON in the chat"));
assert.ok(prompt.includes("Do not shorten, summarize, omit, split, or reduce any financial field"));
assert.ok(prompt.includes("FALLBACK ONLY"));
assert.equal(prompt.includes("fairValueSummary.fairValueBase"), false, "Initial prompt must stay on the V3 contract and not leak legacy fairValueSummary paths.");

const firstBrace = prompt.indexOf("{");
assert.ok(firstBrace > 0, "Prompt must contain one machine-readable request envelope.");
const request = JSON.parse(prompt.slice(firstBrace));

assert.equal(request.promptVersion, "franklin-initial-analysis-prompt/v3");
assert.equal(request.requestType, "FRANKLIN_INITIAL_ANALYSIS");
assert.equal(request.ticker, "NVDA");
assert.equal(request.authority.analyst, "ChatGPT / Fair Value");
assert.equal(request.outputContract.schemaVersion, "franklin-fair-value/v3");
assert.equal(request.outputContract.methodologyVersion, "fair-value-methodology/v2");
assert.equal(request.outputContract.analysisType, "INITIAL");
assert.equal(request.outputContract.format, "DOWNLOADABLE_UTF8_JSON_FILE");
assert.equal(request.outputContract.quarterPeriodRules.exactFormat, "Q{1-4} YYYY");
assert.deepEqual(request.outputContract.quarterPeriodRules.correctExamples, ["Q3 2026", "Q4 2026"]);
assert.equal(request.jsonTemplate.schemaVersion, "franklin-fair-value/v3");
assert.equal(request.jsonTemplate.analysisType, "INITIAL");
assert.deepEqual(Object.keys(request.jsonTemplate.valuation.scenarios), ["Bear", "Base", "Bull"]);
assert.ok(request.analysisScope.fullSceneReading.length >= 5, "Prompt must require a full industry/competitive/macro scene reading when material.");
assert.ok(request.analysisScope.valuation.some((item) => item.includes("Reverse DCF")));
assert.ok(request.analysisScope.decision.some((item) => item.includes("nextRequirements")));
assert.equal(request.researchPolicy.noFabrication, true);
assert.match(request.researchPolicy.comparability, /GAAP\/non-GAAP/);
assert.ok(request.researchPolicy.sourcePriority.includes("Investor Relations"));
assert.ok(request.outputContract.arithmeticChecks.some((item) => item.includes("probabilityWeighted")));
assert.ok(request.outputContract.arithmeticChecks.some((item) => item.includes("weightedMethodFairValue")));
assert.ok(request.completionChecklist.some((item) => item.includes("financialNormalization")));
assert.ok(request.completionChecklist.some((item) => item.includes("المشهد الصناعي")));

assert.ok(prompt.length < 35000, `Initial prompt is unexpectedly large: ${prompt.length} chars.`);

console.log(`Initial analysis prompt contract: PASS (${prompt.length} chars)`);
