import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { externalAnalysisToHomeCard } from "../src/externalAnalysis/reportAdapter.js";
import { normalizeExternalAnalysisReport } from "../src/externalAnalysis/schema.js";
import { dateFieldValue, fieldValue, withCurrentPrice, withPresentation } from "../src/ui/reportPresentationEditor.js";

const source={id:"report-1",company:{ticker:"ACME",name:"Acme"},fairValueSummary:{currentPrice:100,fairValueBase:150},metadata:{franklinV3Report:{marketPrice:{value:100},valuation:{upsideToBasePct:50,marginOfSafetyPct:33.33}}}};
assert.equal(fieldValue(null),"");assert.equal(fieldValue(undefined),"");assert.equal(fieldValue(""),"");assert.equal(fieldValue(0),"");assert.equal(fieldValue(142),"142");
assert.equal(dateFieldValue("2026-11-05"),"2026-11-05");assert.equal(dateFieldValue("2026-02-30"),"");assert.equal(dateFieldValue("05/11/2026"),"");
const repriced=withCurrentPrice(source,120);assert.equal(repriced.fairValueSummary.currentPrice,120);assert.equal(repriced.fairValueSummary.upsideDownsidePercent,25);assert.equal(repriced.fairValueSummary.marginOfSafetyPercent,20);assert.equal(repriced.metadata.franklinV3Report.marketPrice.value,120);assert.equal(repriced.metadata.franklinV3Report.valuation.upsideToBasePct,25);assert.equal(repriced.metadata.franklinV3Report.valuation.marginOfSafetyPct,20);assert.equal(source.fairValueSummary.currentPrice,100);
const logo="data:image/png;base64,aGVsbG8=";const presented=withPresentation(repriced,{companyLogoDataUrl:logo,morningstarFairValue:142,nextEarningsDate:"2026-11-05"});const normalized=normalizeExternalAnalysisReport(presented,"",{now:new Date("2026-08-25T00:00:00Z")});assert.equal(normalized.presentation.companyLogoDataUrl,logo);assert.equal(normalized.presentation.morningstarFairValue,142);assert.equal(normalized.presentation.nextEarningsDate,"2026-11-05");
const card=externalAnalysisToHomeCard(normalized);assert.equal(card.companyLogoDataUrl,logo);assert.equal(card.morningstarFairValue,142);assert.equal(card.currentPrice,120);
const cleared=withPresentation(presented,{companyLogoDataUrl:null,morningstarFairValue:null,nextEarningsDate:null});assert.equal("companyLogoDataUrl" in cleared.presentation,false);assert.equal("morningstarFairValue" in cleared.presentation,false);assert.equal("nextEarningsDate" in cleared.presentation,false);
const editorSource=await readFile(new URL("../src/ui/reportPresentationEditor.js",import.meta.url),"utf8");const mainSource=await readFile(new URL("../src/main.js",import.meta.url),"utf8");const indexSource=await readFile(new URL("../index.html",import.meta.url),"utf8");
assert.match(editorSource,/activePanel\s*===\s*"external-import"/);assert.match(editorSource,/بيانات بطاقة الشركة/);assert.match(editorSource,/insertAdjacentElement\("afterend",\s*section\)/);assert.match(editorSource,/reportNeedsOwnerPresentation/);assert.match(editorSource,/data-owner-presentation-dialog/);assert.match(editorSource,/data-owner-presentation-open/);assert.match(editorSource,/data-owner-next-earnings-date/);assert.match(editorSource,/quarterly-scorecard/);assert.equal(editorSource.includes("localStorage"),false);assert.equal(editorSource.includes("stockWorkspaceNavigation.js"),false);assert.match(mainSource,/reportPresentationEditor\.js\?v=compact-visual-20260901-1/);assert.match(indexSource,/main\.js\?v=compact-visual-20260901-1/);assert.match(indexSource,/styles-visual-system\.css\?v=compact-visual-20260901-1/);
console.log("report presentation editor tests passed");
