import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const nav=readFileSync(new URL("../src/ui/stockWorkspaceNavigation.js",import.meta.url),"utf8");
const editor=readFileSync(new URL("../src/ui/reportPresentationEditor.js",import.meta.url),"utf8");
const styles=readFileSync(new URL("../styles-stock-workspace-v58.css",import.meta.url),"utf8");
const worker=readFileSync(new URL("../service-worker.js",import.meta.url),"utf8");
const sync=readFileSync(new URL("../scripts/sync-deploy.mjs",import.meta.url),"utf8");
for(const page of ["summary","earnings","company","strengths"])assert.ok(nav.includes(`["${page}",`));
assert.ok(nav.includes("openExternalReport"));assert.ok(nav.includes("openQuarterlyScorecard"));assert.ok(nav.includes("openCompanyProfile"));assert.ok(nav.includes("normalizeEarningsTable"));assert.ok(nav.includes("franklin-summary-legacy-earnings-detail"));assert.ok(nav.includes("latest-earnings-summary-section"));assert.equal(nav.includes("localStorage"),false);assert.equal(nav.includes("sessionStorage"),false);
assert.ok(nav.includes("mountedHeader?.parentElement === frame"));
assert.ok(nav.includes('observe(root, { childList: true })'));assert.equal(nav.includes("subtree: true"),false);assert.ok(nav.includes("data-stock-menu-toggle"));assert.ok(nav.includes("data-owner-presentation-open"));assert.ok(nav.includes('dialog.setAttribute("open", "")'));
assert.ok(styles.includes("franklin-stock-workspace-active .mobile-bottom-nav"));assert.ok(styles.includes("franklin-stock-page-tabs"));assert.ok(styles.includes("fet-section-tabs"));assert.ok(styles.includes("fet-table-unified"));assert.ok(styles.includes("text-align: right"));assert.ok(styles.includes("text-align: left"));
assert.equal(editor.includes("stockWorkspaceNavigation.js"),false);assert.ok(editor.includes("owner-presentation-dialog"));assert.ok(editor.includes("data-owner-presentation-open"));assert.ok(editor.includes("بيانات بطاقة الشركة"));assert.ok(editor.includes("function openDialog"));assert.ok(editor.includes("function closeDialog"));assert.equal(editor.includes("<details open>"),false);
assert.ok(worker.includes("compact-visual-20260901-1"));assert.ok(worker.includes("styles-stock-workspace-v58.css"));assert.ok(worker.includes("stockWorkspaceNavigation.js"));assert.ok(sync.includes("styles-stock-workspace-v58.css"));
console.log("Franklin stock workspace v58 contract passed.");
